# Generated by Django 6.0.2 on 2026-02-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reagente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reagente_nome', models.CharField(max_length=200)),
                ('fispq', models.CharField(max_length=50)),
                ('armario', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('validade', models.DateField(verbose_name='data de validade')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('controlador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagente_controlador', to='reagents.controlador')),
                ('coordenacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagente_coordenacao', to='reagents.coordenacao')),
            ],
        ),
    ]
