# Generated by Django 6.0.2 on 2026-02-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagente',
            name='coordenacao',
        ),
        migrations.RemoveField(
            model_name='reagente',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='reagente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reagente',
            name='controlador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagentes', to='reagents.controlador'),
        ),
        migrations.CreateModel(
            name='SaidaReagente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitante', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('coordenacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reagents.coordenacao')),
                ('reagente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reagents.reagente')),
            ],
        ),
        migrations.CreateModel(
            name='ReagenteCoordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('coordenacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reagents.coordenacao')),
                ('reagente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.reagente')),
            ],
            options={
                'unique_together': {('reagente', 'coordenacao')},
            },
        ),
    ]
