# Generated by Django 6.0.2 on 2026-02-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reagents', '0002_remove_reagente_coordenacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coord', 'Usuário da Coordenação')], default='coord', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='coordenacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reagents.coordenacao'),
        ),
    ]
