# Generated by Django 6.0.2 on 2026-03-01 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_tipo_alter_perfil_coordenacao'),
        ('reagents', '0002_remove_reagente_coordenacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'admin'), ('coordenacao__isnull', True)), models.Q(('tipo', 'coord'), ('coordenacao__isnull', False)), _connector='OR'), name='perfil_admin_sem_coordenacao_ou_coord_com_coordenacao'),
        ),
    ]
